name: Build
on:
    push:
        tags:
        - '*.*.*-rc.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3
      with:
        ref: main

    - name: Use Node.js 18 LTS
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Gulp
      run: npm install -g gulp-cli
    
    - name: Cache dependencies
      uses: actions/cache@v3
      id: npmcache
      with:
        path: node_modules
        key: cache-dependencies-${{ hashFiles('**/package-lock.json') }}

    - name: Install other dependencies
      if: steps.npmcache.outputs.cache-hit != 'true'
      run: npm install

    - name: Build generic
      run: gulp generic

    - name: Minify-JS Action
      uses: jossydevers/minify-js@v1.0.0
      with:
        directory: 'build/generic/web/viewer.js' # (OPTIONAL)
        output: 'build/generic/web/viewer.min.js' # (OPTIONAL)
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build
        retention-days: 10
