name: Build
on:
    push:
        tags:
        - '*.*.*-rc.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18 LTS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Gulp
        run: npm install -g gulp-cli

      - name: Install other dependencies
        run: npm install

      - name: Build the website
        run: gulp web
      
      - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build/gh-pages
        retention-days: 10