name: Test
on:
  push:
    branches:
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    - name: Use Node.js 10 LTS
      uses: actions/setup-node@v3
      with:
        node-version: '10'

    - name: Install other dependencies
      run: npm install
    
    - name: Install Gulp
      run: npm install -g gulp-cli

    - name: Build generic
      run: gulp generic
    
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        path: build
        retention-days: 10